### ISSUE TITLE
The popup for Misc-info and Full Definition is not working

### ISSUE THREAD

**Issue by Hanamizuiro** [rudnam/JP-study#2]
Today, I tried your anki mining template, I tried to import vocabulary words via Yomichan, however upon testing out the cards I have imported, the popup function to display the full definition is not working for me. 

![1](https://github.com/rudnam/JP-study/assets/37798951/e12fd37e-2d11-44ea-9f23-d23e0d51a1ee)
You can see the check-box at the bottom right is already checked, but the misc. info and full definition functions remain non-existent.

**Comment by rudnam** [comment]
That's strange. Can you try replacing the back template with this one: [back_template.txt](https://github.com/rudnam/JP-study/files/12473475/back_template.txt)

**Comment by Hanamizuiro** [comment]
Just got back from school. I replaced it with the file you attached and sad to say that It still not working.
![image](https://github.com/rudnam/JP-study/assets/37798951/1e92b39b-e001-46a5-be62-24da88cb25bd)

**Comment by Hanamizuiro** [comment]
I just redownloaded the anki notes since I have seen the file were updated yesterday and everything works fine now. Thank you very much.
![image](https://github.com/rudnam/JP-study/assets/37798951/a195048a-e040-4553-a79f-33bd361d9955)
