### ISSUE TITLE
IPA symbols don't show up in Ankidroid

### ISSUE THREAD

**Issue by FoundNull** [rudnam/JP-study#3]
Hello! A few days ago, I attempted to add IPA transcription to my cards. However, I noticed that certain symbols were not recognized. Even after changing the font, I was still unable to fix the issue. 

It is worth mentioning that this problem only occurs in specific fields:

![Screenshot_20240329-120331_AnkiDroid~2](https://github.com/rudnam/JP-study/assets/161540846/8ce323f7-4297-4869-aaa9-836c5b6ac455)
![Screenshot_20240329-120420_AnkiDroid~3](https://github.com/rudnam/JP-study/assets/161540846/9495dc43-6164-4e4a-a4f8-c9b33cc22b01)

**Comment by rudnam** [comment]
Hi, can you try to find `.info` in the Styling part of the template and replace it with this:

```diff
.info {
  font-size: calc(var(--main-font-size) * 1.5);
  font-family: var(--sub-font);
}
```

**Comment by FoundNull** [comment]
That worked. Thank you very much!
