### ISSUE TITLE
do you have a video explaining how to set up this template?

### ISSUE THREAD

**Issue by ghost** [rudnam/JP-study#7]
hello, i'm using jp mining note but I loved this template! i've tried to set it up myself 2 times but i'm a bit too dumb to do it myself.. do you have a step-by-step video?

**Comment by rudnam** [comment]
Hi! Glad you like it! Essentially you just download the deck, then set it as your card type on Yomitan (like [this](https://arbyste.github.io/jp-mining-note/setupyomichan/#yomichan-fields) but choose Mining-JP).

If you haven't set up anki and/or yomitan yet it should be the same as the existing tutorials for JP mining note

**Comment by ghost** [comment]
Hello~ thank you! its working now but I have some questions..
When I mine a word, it doesn't automatically insert an image into the card, even if I set the “image” field to {image} it doesn't work.. How do you usually add images? do you do it manually with programs like sharex? 
i'm also having a problem with the “hint” field. i'd like to put it on the front of the card (leave it hidden unless I want to see it) i've tried {hint} or {1} but none of them worked..

**Comment by rudnam** [comment]
Adding images to cards doesn't really work well with yomitan, most people add them through other programs like ShareX and ASBPlayer.
For the hint field its normally not filled through yomitan but through manually adding hints to the specific cards you want. So just fill up the field through anki whenever you want to add a hint
