### ISSUE TITLE
Pitch accent color not showing on the words

### ISSUE THREAD

**Issue by Kib843** [rudnam/JP-study#8]
I just started using the note type and it works and looks great! I haven't been able to figure out how to show the colors of the words on the cards (aside from the pitch accent on the furigana)

For reference:
![Screenshot 2024-10-11 110057](https://github.com/user-attachments/assets/1511fd64-a142-4395-b3f5-f979ceb94a17)
![Screenshot 2024-10-11 110118](https://github.com/user-attachments/assets/aafe44b4-8c81-4e07-a955-d1e0eb4f67b4)

Oddly enough, it seems to work just fine for word definition cards, but not when I have "x" put in for the "*IsSentenceCard" field.

Is this automatically generated during card creation or do I have to manually do it in the card creation?

**Comment by rudnam** [comment]
In Yomitan can you check if the template for the Sentence field is `{cloze-prefix}<b>{cloze-body}</b>{cloze-suffix}`?

If the template's correct then can you try mining another sentence because there seems to be a space in between the kanji for 中国 which might make it not work

**Comment by Kib843** [comment]
Sure! The field seems to be correctly filled out.
![image](https://github.com/user-attachments/assets/4ff649b1-838e-4c65-b48a-34a768c32413)

![image](https://github.com/user-attachments/assets/1da6eaf0-5129-488d-9f06-7426b24f9936)
![image](https://github.com/user-attachments/assets/3ec272ef-cf74-4a56-b46d-45a7dc9f85ed)

It works just fine when I have nothing filled in *IsSentenceCard. I have "x" filled in for this field in Yomitan itself, not Anki, which I'm not sure if that has something to do with it, but testing it out didn't seem to fix it.
![image](https://github.com/user-attachments/assets/8da4ca89-e919-4ab9-9d12-8e303b2488c4)

**Comment by rudnam** [comment]
Ah, it's because you filled up the SentenceFurigana field so that's what's getting displayed. {sentence-furigana} doesnt have the `<b>` tags

**Comment by Kib843** [comment]
Got it, it works now without that filled in now! Is there something I can put in that field so it still generates the sentence furigana, or should I use another plug-in on Anki to fill it out automatically?

**Comment by rudnam** [comment]
Yeah what I did back then was use the AJT Japanese add-on to generate the furigana while keeping the `<b>` tags

**Comment by Kib843** [comment]
Awesome it works perfectly now! Thank you so much for your help!
